// Automated Model Discovery Results - 2025-09-04
// Generated by automated_model_discovery.py

export const DISCOVERED_MODELS = {
  'anthropic': [
    // Discovered from https://docs.anthropic.com/claude/...
    // Source: https://docs.anthropic.com/claude/docs/models-overview
    // Confidence: 0.7
    'claude-3-haiku-20240307',
    // Discovered from https://docs.anthropic.com/claude/...
    // Source: https://docs.anthropic.com/claude/docs/models-overview
    // Confidence: 0.7
    'claude-3-haiku',
  ], // 2 models

  'google': [
    // Discovered from https://ai.google.dev/gemini-api/d...
    // Source: https://ai.google.dev/gemini-api/docs/models/gemini
    // Confidence: 0.7
    'gemini-1.5-flash',
    // Discovered from https://ai.google.dev/gemini-api/d...
    // Source: https://ai.google.dev/gemini-api/docs/models/gemini
    // Confidence: 0.7
    'gemini-1.5-pro',
    // Discovered from https://ai.google.dev/gemini-api/d...
    // Source: https://ai.google.dev/gemini-api/docs/models/gemini
    // Confidence: 0.7
    'gemini-1.5-flash-001',
    // Discovered from https://ai.google.dev/gemini-api/d...
    // Source: https://ai.google.dev/gemini-api/docs/models/gemini
    // Confidence: 0.7
    'gemini-1.5-flash-002',
    // Discovered from https://ai.google.dev/gemini-api/d...
    // Source: https://ai.google.dev/gemini-api/docs/models/gemini
    // Confidence: 0.7
    'gemini-1.5-pro-001',
    // Discovered from https://ai.google.dev/gemini-api/d...
    // Source: https://ai.google.dev/gemini-api/docs/models/gemini
    // Confidence: 0.7
    'gemini-1.5-pro-002',
  ], // 6 models

  'mistral': [
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mistral-medium',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mistral-large',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mistral-small',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mistral-medium-latest',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mistral-large-latest',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mistral-small-latest',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'Codestral',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'codestral',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'codestral-latest',
    // Discovered from https://docs.mistral.ai/getting-st...
    // Source: https://docs.mistral.ai/getting-started/models/
    // Confidence: 0.7
    'mixtral-8x7b',
  ], // 10 models

  'deepseek': [
    // Discovered from https://arxiv.org/search/?query=de...
    // Source: https://arxiv.org/search/?query=deepseek&searchtype=all
    // Confidence: 0.7
    'DeepSeek-Coder',
    // Discovered from https://arxiv.org/search/?query=de...
    // Source: https://arxiv.org/search/?query=deepseek&searchtype=all
    // Confidence: 0.7
    'DeepSeek-R1',
    // Discovered from https://arxiv.org/search/?query=de...
    // Source: https://arxiv.org/search/?query=deepseek&searchtype=all
    // Confidence: 0.7
    'deepseek-r1-distill',
    // Discovered from https://arxiv.org/search/?query=de...
    // Source: https://arxiv.org/search/?query=deepseek&searchtype=all
    // Confidence: 0.7
    'DeepSeek-R1-Distill',
    // Discovered from https://arxiv.org/search/?query=de...
    // Source: https://arxiv.org/search/?query=deepseek&searchtype=all
    // Confidence: 0.7
    'Deepseek-R1',
    // Discovered from https://arxiv.org/search/?query=de...
    // Source: https://arxiv.org/search/?query=deepseek&searchtype=all
    // Confidence: 0.7
    'DeepSeek-r1',
  ], // 6 models

};

// Total discovered: 24 models
// Providers with models: 4