-- Referral System Schema
-- Tables for tracking referral codes, relationships, and rewards

-- Table for storing referral codes
CREATE TABLE IF NOT EXISTS referral_codes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    code VARCHAR(20) NOT NULL UNIQUE,
    uses_remaining INTEGER NOT NULL DEFAULT 100,
    total_uses INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Index for faster code lookups
CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON referral_codes(code);
CREATE INDEX IF NOT EXISTS idx_referral_codes_user_id ON referral_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_referral_codes_active ON referral_codes(is_active, uses_remaining);

-- Table for tracking referral relationships and rewards
CREATE TABLE IF NOT EXISTS user_referrals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    referrer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    referred_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    referral_code VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    rewards_given JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    
    -- Ensure a user can only be referred once
    CONSTRAINT unique_referred_user UNIQUE (referred_user_id),
    -- Ensure users can't refer themselves
    CONSTRAINT no_self_referral CHECK (referrer_id != referred_user_id)
);

-- Indexes for referral queries
CREATE INDEX IF NOT EXISTS idx_user_referrals_referrer ON user_referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_user_referrals_referred ON user_referrals(referred_user_id);
CREATE INDEX IF NOT EXISTS idx_user_referrals_status ON user_referrals(status);
CREATE INDEX IF NOT EXISTS idx_user_referrals_created_at ON user_referrals(created_at);

-- RLS Policies
ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_referrals ENABLE ROW LEVEL SECURITY;

-- Referral codes policies
CREATE POLICY "Users can view their own referral codes"
    ON referral_codes FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own referral codes"
    ON referral_codes FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own referral codes"
    ON referral_codes FOR UPDATE
    USING (auth.uid() = user_id);

-- User referrals policies
CREATE POLICY "Users can view referrals they made or were part of"
    ON user_referrals FOR SELECT
    USING (auth.uid() = referrer_id OR auth.uid() = referred_user_id);

CREATE POLICY "System can insert referral records"
    ON user_referrals FOR INSERT
    WITH CHECK (true); -- Will be restricted by service role in application code

CREATE POLICY "System can update referral records"
    ON user_referrals FOR UPDATE
    USING (true); -- Will be restricted by service role in application code

-- Function to get referral stats (optimized query)
CREATE OR REPLACE FUNCTION get_user_referral_stats(user_uuid UUID)
RETURNS TABLE (
    total_referrals BIGINT,
    completed_referrals BIGINT,
    pending_referrals BIGINT,
    this_month_referrals BIGINT,
    total_credits_earned NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*) as total_referrals,
        COUNT(*) FILTER (WHERE status = 'completed') as completed_referrals,
        COUNT(*) FILTER (WHERE status = 'pending') as pending_referrals,
        COUNT(*) FILTER (WHERE DATE_TRUNC('month', created_at) = DATE_TRUNC('month', CURRENT_TIMESTAMP)) as this_month_referrals,
        COALESCE(SUM((rewards_given->>'referrer_credits')::numeric), 0) as total_credits_earned
    FROM user_referrals
    WHERE referrer_id = user_uuid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION get_user_referral_stats(UUID) TO authenticated;

COMMENT ON TABLE referral_codes IS 'Stores referral codes generated by users';
COMMENT ON TABLE user_referrals IS 'Tracks referral relationships and rewards between users';
COMMENT ON FUNCTION get_user_referral_stats(UUID) IS 'Returns referral statistics for a given user';